config/routes.rb
Sales::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  
  resources :attempts do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
  end
  resources :sales do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
    
    resources :sale_items
  end
  resources :companies
  
  resources :campaigns do
    resources :products
  end
  
  resources :users

  get "pages/home"
  get "pages/about"
  get "pages/release_notes"
  
  root :to => "pages#home"
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  # associations
  belongs_to :campaign
  belongs_to :company
  belongs_to :user
  
  #validations
  validates_presence_of :campaign_id
  validates_presence_of :company_id
  validates_presence_of :user_id
  validates_numericality_of :value, :greater_than_or_equal_to => 0,
                                    :allow_nil => true
  
  #scopes
  scope :sales, where("value > 0")
  scope :emailed, where(:email => true)
  scope :reverse_chronological, order("created_at DESC")
  
  def campaign_name
    campaign.title if campaign
  end
  
  def campaign_name=(name)
    self.campaign = Campaign.find_by_title(name)
  end
  
  def company_name
    company.title if company
  end
  
  def company_name=(name)
    self.company = Company.find_by_title(name)
  end
  
  # returns a string which includes the year and day of year for an attempt
  def year_day
    self.created_at.strftime('%Y %j')
  end
  
end




# == Schema Information
#
# Table name: attempts
#
#  id          :integer         primary key
#  user_id     :integer
#  email       :boolean
#  phone       :boolean
#  fax         :boolean
#  created_at  :timestamp
#  updated_at  :timestamp
#  company_id  :integer
#  campaign_id :integer
#  verbal      :boolean
#  value       :integer
#

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_filter :require_user
  before_filter :require_admin, :only => [:destroy]
  
  autocomplete :campaign, :title, :full => true
  autocomplete :company, :title, :full => true
  
  # GET /attempts
  # GET /attempts.xml
  def index
    @attempts = Attempt.reverse_chronological.page(params[:page])
    @title = "Contact Attempts"
  end

  # GET /attempts/1
  # GET /attempts/1.xml
  def show
    @attempt = Attempt.find(params[:id])
    @title = "Attempt ##{@attempt.id}"
  end

  # GET /attempts/new
  # GET /attempts/new.xml
  def new
    @attempt = Attempt.new
    @attempt.campaign_id = 7
    @attempt.company = current_user.companies.last
    @attempt.user = current_user
    @title = "New Contact Attempt"
  end

  # GET /attempts/1/edit
  def edit
    @attempt = Attempt.find(params[:id])
    @title = "Editing Attempt"
  end

  # POST /attempts
  # POST /attempts.xml
  def create
    @attempt = Attempt.new(params[:attempt])

    if @attempt.save
      redirect_to(attempts_path, :flash => { :success => 'Contact Attempt successfully created' })
    else
      @title = "New Contact Attempt"
      render :action => "new"
    end
  end

  # PUT /attempts/1
  # PUT /attempts/1.xml
  def update
    @attempt = Attempt.find(params[:id])

    if @attempt.update_attributes(params[:attempt])
      redirect_to(@attempt, :flash => { :success => 'Contact Attempt successfully updated' })
    else
      @title = "Editing Attempt"
      render :action => "edit"
    end
  end

  # DELETE /attempts/1
  # DELETE /attempts/1.xml
  def destroy
    @attempt = Attempt.find(params[:id])
    @attempt.destroy

    redirect_to(attempts_url)
  end
end

app/views/attempts/_attempt.html.haml
%li
	= attempt.created_at.strftime("%A, %B %d, %Y, %l:%M %P")
	= link_to "Details", attempt

app/views/attempts/_form.html.haml
= form_for(@attempt) do |f|
	-if @attempt.errors.any?
		#error_explanation
			%h2= "#{pluralize(@attempt.errors.count, "error")} prohibited this attempt from being saved:"

			%ul
				- @attempt.errors.full_messages.each do |msg|
					%li= msg

	= f.hidden_field :user_id

	.field
		= f.label :campaign_name
		= f.autocomplete_field :campaign_name, autocomplete_campaign_title_attempts_path

	.field
		= f.label :company_name
		= f.autocomplete_field :company_name, autocomplete_company_title_attempts_path, :autofocus => true

	.field
		.checkbox
			= f.label :phone
			= f.check_box :phone
			%br
		.checkbox
			= f.label :email
			= f.check_box :email
			%br
		.checkbox
			= f.label :fax
			= f.check_box :fax
			%br
	.clear

	%h2 Sales Stats
	.field
		= f.label :verbal
		= f.check_box :verbal

		
	%div
		.field
			= f.label :value
			= f.text_field :value
	
	.actions
		= f.submit

app/views/attempts/edit.html.haml
%h1 Editing Attempt

= render 'form'
= link_to 'Show', @attempt
|
= link_to 'Back', attempts_path

app/views/attempts/index.html.haml
%h1 Listing attempts

%p= link_to 'New Attempt', new_attempt_path

%table.styled
	%thead
		%tr
			%th{ :width => 170 } Time
			%th Company
			%th{ :width => 125 } Estimated Value
			%th{ :width => 75 } Verbal
			%th{ :width => 100 } &nbsp;

	%tbody
		- @attempts.each do |attempt|
			%tr
				%td{ :align => "center" }= attempt.created_at.strftime("%A, %B %d, %Y %l:%M %P")
				%td= attempt.company.title if attempt.company
				%td{ :align => "center" }= number_to_currency attempt.value
				%td{ :align => "center" }= attempt.verbal ? 'Yes' : ''
				%td{ :align => "center" }
					= link_to 'Show', attempt
					= link_to 'Edit', edit_attempt_path(attempt)
					- if current_user.admin
						= link_to "Delete", attempt, :method => "delete", :confirm => "Are you sure you want to delete this contact attempt? It is completely permanent!"

	- if @attempts.total_pages > 1
		%tfoot
			%tr
				%td{ :colspan => 7, :align => "center" }
					= will_paginate @attempts, :class => "digg_pagination"

%p= link_to 'New Attempt', new_attempt_path

app/views/attempts/new.html.haml
%h1 New attempt

= render 'form'
= link_to 'Back', attempts_path

app/views/attempts/show.html.haml
%p
	%strong Campaign:
	= @attempt.campaign.title if @attempt.campaign
	%br
	= @attempt.created_at.strftime("Contact made on %A, %B %d, %Y %l:%M %P")

%p
	%strong Company:
	= link_to(@attempt.company.title, @attempt.company) if @attempt.company

%p
	%strong Email:
	= @attempt.email

%p
	%strong Phone:
	= @attempt.phone

%p
	%strong Fax:
	= @attempt.fax

%p
	%strong Verbal:
	= @attempt.verbal ? 'Yes' : 'No'
	
= link_to 'Edit', edit_attempt_path(@attempt)
|
= link_to 'Back', attempts_path