config/routes.rb
Sales::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  
  resources :attempts do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
  end
  resources :sales do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
    
    resources :sale_items
  end
  resources :companies
  
  resources :campaigns do
    resources :products
  end
  
  resources :users

  get "pages/home"
  get "pages/about"
  get "pages/release_notes"
  
  root :to => "pages#home"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :company
  belongs_to :user
  has_many :sale_items, :dependent => :destroy
  
  accepts_nested_attributes_for :sale_items, :allow_destroy => true, :reject_if => lambda { |a| a[:product_id].blank? }
  
  validates_presence_of :campaign_id
  validates_presence_of :company_id
  validates_presence_of :user_id
  serialize :values
  
  scope :reverse_chronological, order("created_at DESC")
  
  def year_day
    self.created_at.strftime('%Y %j')
  end
end


# == Schema Information
#
# Table name: sales
#
#  id                           :integer         primary key
#  total                        :integer
#  company_id                   :integer
#  campaign_id                  :integer
#  created_at                   :timestamp
#  updated_at                   :timestamp
#  user_id                      :integer
#  carrot                       :integer
#  off_campus                   :integer         default(0), not null
#  off_campus_value             :integer         default(0), not null
#  off_campus_duration          :integer         default(0), not null
#  off_campus_featured          :integer         default(0), not null
#  off_campus_featured_value    :integer         default(0), not null
#  off_campus_featured_duration :integer         default(0), not null
#  restaurant                   :integer         default(0), not null
#  restaurant_value             :integer         default(0), not null
#  restaurant_duration          :integer         default(0), not null
#  restaurant_featured          :integer         default(0), not null
#  restaurant_featured_value    :integer         default(0), not null
#  restaurant_featured_duration :integer         default(0), not null
#  services                     :integer         default(0), not null
#  services_value               :integer         default(0), not null
#  services_duration            :integer         default(0), not null
#  services_featured            :integer         default(0), not null
#  services_featured_value      :integer         default(0), not null
#  services_featured_duration   :integer         default(0), not null
#  email_blast                  :integer         default(0), not null
#  email_blast_value            :integer         default(0), not null
#  ads                          :integer         default(0), not null
#  ads_value                    :integer         default(0), not null
#  off_campus_carrots           :integer         default(0), not null
#  restaurant_carrots           :integer         default(0), not null
#  service_carrots              :integer         default(0), not null
#  values                       :text
#

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_filter :require_user
  before_filter :require_admin, :only => [:destroy]
  
  autocomplete :campaign, :title, :full => true
  autocomplete :company, :title, :full => true
  
  # GET /sales
  def index
    @sales = Sale.reverse_chronological.page(params[:page])
    @title = "Sales"
  end

  # GET /sales/1
  def show
    @sale = Sale.find(params[:id])
    @title = "Sale ##{@sale.id}"
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @sale.campaign_id = 7
    @sale.user = current_user
    @title = "New Sale"
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
    @title = "Editing Sale"
  end

  # POST /sales
  def create
    @sale = Sale.new(params[:sale])

    if @sale.save
      redirect_to(edit_sale_path(@sale), :flash => { :success => 'Sale successfully created' })
    else
      @title = "New Sale"
      render :action => "new"
    end
  end

  # PUT /sales/1
  def update
    @sale = Sale.find(params[:id])

    if @sale.update_attributes(params[:sale])
      redirect_to(edit_sale_path(@sale), :flash => { :success => 'Sale successfully updated' })
    else
      @title = "Editing Sale"
      render :action => "edit"
    end
  end

  # DELETE /sales/1
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    
    redirect_to(sales_path)
  end
end

app/views/sales/_form.html.haml
= form_for(@sale) do |f|
	- if @sale.errors.any?
		#error_explanation
			%h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"

			%ul
				- @sale.errors.full_messages.each do |msg|
					%li= msg

	= f.hidden_field :user_id

	.field
		= label :campaign_name, :campaign_name
		= f.hidden_field :campaign_id
		= autocomplete_field_tag :campaign_name, @sale.campaign ? @sale.campaign.title : '', autocomplete_campaign_title_sales_path, :id_element => "#sale_campaign_id"

	.field
		= label :company_name, :company_name
		= f.hidden_field :company_id
		= autocomplete_field_tag :company_name, @sale.company ? @sale.company.title : '', autocomplete_company_title_sales_path, :id_element => '#sale_company_id', :autofocus => true
		
	.field
		= f.label :total
		= f.text_field :total

	.actions
		= f.submit
		
	- if @sale.campaign
		%h2 Products
		#saleItems
			= f.fields_for :sale_items do |builder|
				= render 'products/product', :product => builder.object.product, :f => builder

- unless @sale.new_record?
	= form_for [@sale, @sale.sale_items.build] do |f|
		= f.collection_select(:product_id, @sale.campaign.products, :id, :title)
		= f.submit :Add

app/views/sales/edit.html.haml
%h1 Editing sale

= render 'form'
= link_to 'Show', @sale
|
= link_to 'Back', sales_path

app/views/sales/index.html.haml
%h1 Sales

%p= link_to 'New Sale', new_sale_path

%table.styled
	%thead
		%tr
			%th{ :width => 100 } Total
			%th Company
			%th Campaign
			%th{ :width => 100 }

	%tbody
		- @sales.each do |sale|
			%tr
				%td{ :align => "center" }= number_to_currency sale.total
				%td= sale.company.title if sale.company
				%td= sale.campaign.title
				%td{ :align => "center" }
					= link_to 'Show', sale
					= link_to 'Edit', edit_sale_path(sale)
					- if current_user.admin
						= link_to "Delete", sale, :method => "delete", :confirm => "Are you sure you want to delete this sale? It is completely permanent!"

	- if @sales.total_pages > 1
		%tfoot
			%tr
				%td{ :colspan => 5, :align => "center" }
					= will_paginate @sales, :class => 'digg_pagination'

%p= link_to 'New Sale', new_sale_path

app/views/sales/new.html.haml
%h1 New Sale

= render 'form'
= link_to 'Back', sales_path

app/views/sales/show.html.haml
%p
	%strong Company:
	= !@sale.company.nil? ? link_to(@sale.company.title, @sale.company) : ''

%p
	%strong Campaign:
	= !@sale.campaign.nil? ? link_to(@sale.campaign.title, @sale.campaign) : ''
	
%p
	%strong Total:
	= number_to_currency @sale.total
	%br
	%strong Carrot:
	= number_to_currency @sale.carrot
	%br
	%strong Off Campus Carrots: 
	= @sale.off_campus_carrots
	%br
	%strong Restaurant Carrots: 
	= @sale.restaurant_carrots
	%br
	%strong Service Carrots: 
	= @sale.service_carrots
	
	
%h2 Sale Details
%table
	%tr
		%th Type
		%th{ :width => 50 } Count
		%th{ :width => 150 } Value
		%th{ :width => 150 } Total Quantity

	- @sale.sale_items.group_by(&:product_id).each do |index, items|
		%tr
			%td= items.first.product.title
			%td{ :align => 'center' }= items.count
			%td{ :align => 'center' }= number_to_currency items.collect(&:price).sum
			%td{ :align => 'center' }= "#{items.collect(&:quantity).sum} #{items.first.product.quantity_label}"
%p
	= link_to 'Edit', edit_sale_path(@sale)
	|
	= link_to 'Back', sales_path