config/routes.rb
Sales::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  
  resources :attempts do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
  end
  resources :sales do
    get :autocomplete_campaign_title, :on => :collection
    get :autocomplete_company_title, :on => :collection
    
    resources :sale_items
  end
  resources :companies
  
  resources :campaigns do
    resources :products
  end
  
  resources :users

  get "pages/home"
  get "pages/about"
  get "pages/release_notes"
  
  root :to => "pages#home"
end

app/views/layouts/_navigation.html.haml
%ul.menu
	%li= link_to 'Campaigns', campaigns_path
	%li= link_to 'Companies', companies_path
	%li= link_to 'Contact Attempts', attempts_path
	%li= link_to 'Sales', sales_path
	%li= link_to	'Release Notes', pages_release_notes_path
	- if current_user && current_user.admin
		%li= link_to "Users", users_path
	- if current_user
		%li= link_to "Logout", logout_path
	- else
		%li= link_to "Login", login_path

app/views/layouts/_user_details.html.haml
- if current_user
	.div
		= current_user.email
		%br
		Campaign: current_campaign

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= title
		= stylesheet_link_tag "application"
		= javascript_include_tag "application"
		= csrf_meta_tag

	%body
		#navigation
			%div.line.container
				%div.unit.size1of5
					= render 'layouts/user_details'
				%div.unit.size4of5.lastUnit
					= render 'layouts/navigation'
		

		#wrapper.container
			%div
				- flash.each do |key, value|
					%div.flash{ :class => key }
						= value
						
				= yield